const CardImages = {
  '2♣': require('./2_of_clubs.svg'),
  '2♦': require('./2_of_diamonds.svg'),
  '2♥': require('./2_of_hearts.svg'),
  '2♠': require('./2_of_spades.svg'),
  '3♣': require('./3_of_clubs.svg'),
  '3♦': require('./3_of_diamonds.svg'),
  '3♥': require('./3_of_hearts.svg'),
  '3♠': require('./3_of_spades.svg'),
  '4♣': require('./4_of_clubs.svg'),
  '4♦': require('./4_of_diamonds.svg'),
  '4♥': require('./4_of_hearts.svg'),
  '4♠': require('./4_of_spades.svg'),
  '5♣': require('./5_of_clubs.svg'),
  '5♦': require('./5_of_diamonds.svg'),
  '5♥': require('./5_of_hearts.svg'),
  '5♠': require('./5_of_spades.svg'),
  '6♣': require('./6_of_clubs.svg'),
  '6♦': require('./6_of_diamonds.svg'),
  '6♥': require('./6_of_hearts.svg'),
  '6♠': require('./6_of_spades.svg'),
  '7♣': require('./7_of_clubs.svg'),
  '7♦': require('./7_of_diamonds.svg'),
  '7♥': require('./7_of_hearts.svg'),
  '7♠': require('./7_of_spades.svg'),
  '8♣': require('./8_of_clubs.svg'),
  '8♦': require('./8_of_diamonds.svg'),
  '8♥': require('./8_of_hearts.svg'),
  '8♠': require('./8_of_spades.svg'),
  '9♣': require('./9_of_clubs.svg'),
  '9♦': require('./9_of_diamonds.svg'),
  '9♥': require('./9_of_hearts.svg'),
  '9♠': require('./9_of_spades.svg'),
  '10♣': require('./10_of_clubs.svg'),
  '10♦': require('./10_of_diamonds.svg'),
  '10♥': require('./10_of_hearts.svg'),
  '10♠': require('./10_of_spades.svg'),
  'A♣': require('./ace_of_clubs.svg'),
  'A♦': require('./ace_of_diamonds.svg'),
  'A♥': require('./ace_of_hearts.svg'),
  'A♠': require('./ace_of_spades.svg'),
  'J♣': require('./jack_of_clubs.svg'),
  'J♦': require('./jack_of_diamonds.svg'),
  'J♥': require('./jack_of_hearts.svg'),
  'J♠': require('./jack_of_spades.svg'),
  'K♣': require('./king_of_clubs.svg'),
  'K♦': require('./king_of_diamonds.svg'),
  'K♥': require('./king_of_hearts.svg'),
  'K♠': require('./king_of_spades.svg'),
  'Q♣': require('./queen_of_clubs.svg'),
  'Q♦': require('./queen_of_diamonds.svg'),
  'Q♥': require('./queen_of_hearts.svg'),
  'Q♠': require('./queen_of_spades.svg'),
}

export default CardImages

